config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :people
   root 'groups#index'
   get 'change_sensei/:id' => 'groups#update_sensei', as: 'updatesensei'
   get 'randomize' => 'groups#random_people'
   get 'clearteam/:id' => 'groups#clearteam', as: 'clearteam'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :person
  delegate :group_id, :sensei, :to => :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :clearteam]
  before_action :set_personne, only: [:update_sensei]
  before_action :minim_group, only: [:random_people]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @people = Person.all
  end

def update_sensei
  parse = @person.sensei
  if parse
    @person.sensei = false
  else
    @person.sensei = true
end
@person.save

redirect_to :root
end


def clearteam
  team = Person.all
  team.each do |person|
  if person.group_id == @group.id
    person.group_id = nil
    person.save
  end
end
redirect_to :root
end

#algo random
  # def random_people
  #   @groups = Group.all
  #   @people = Person.all
  #
  #   my_max_group = (@people.size / @groups.size).ceil + 1
  #   id_group = []
  #
  #   @people.each do |p|
  #     p.group_id = 0
  #     p.sensei = false
  #     p.save
  #   end
  #
  #   @groups.each do |group|
  #     id_group << group.id
  #   end
  #
  #   @people.each do |i|
  #     random_group = id_group.sample
  #     i.group_id = random_group
  #       i.save
  #     if @people.where(group_id: random_group).size == my_max_group
  #       id_group.delete(random_group)
  #     end
  # end
  # redirect_to root_path

def random_people
   idperson = Person.all.map{|x| x.id}
   Person.all.each do |p|
      p.group_id = 0
      p.sensei = false
      p.save
   end
   if Group.all.count>0
     while idperson.count >0
       Group.all.each do |grp|
         a = idperson.sample
         Person.find(a).update_attributes(group_id: grp.id) unless a.nil?
         ## summarize that:
         # b = Person.find(a)
         # b.group_id = grp.id
         # b.save
         idperson.delete(a)
       end
     end
     redirect_to :root, notice: "Yataî  all has been randomized!!!"

     else
       redirect_to :root, notice: "ther have to be a least one group"
     end

 end


  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
      team = Person.all
      team.each do |person|
      if person.group_id == @group.id
        person.group_id = nil
        person.save
      end
    end
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end
    def set_personne
      @person = Person.find(params[:id])
    end

def minim_group
if Group.all.size < 2
  redirect_to root_path, notice: "il manque le nombre de groupe"
end
end
    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name_group, :salle, :tache)
    end
    def person_params
    params.require(:person).permit(:name, :group_id, :sensei)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :tel, :group_id, :sensei)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_group %><br>
    <%= f.text_field :name_group %>
  </div>
  <div class="field">
    <%= f.label :salle %><br>
    <%= f.text_field :salle %>
  </div>
  <div class="field">
    <%= f.label :tache %><br>
    <%= f.text_field :tache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organisation</h1>

<header class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo" class="navbar-brand">
        <%= link_to "OrganiZation", root_path %>
      </div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Utilisateurs",  people_path %></li>
        </ul>
      </nav>
    </header>

    <table class="table table">
      <thead>
        <tr>
          <th>Name group</th>
          <th>Salle</th>
          <th>Tache</th>
          <th colspan="3"></th>
          <th>content</th>
        </tr>
      </thead>

      <tbody>
        <% @groups.each do |group| %>
        <tr>
          <td><%= group.name_group %></td>
          <td><%= group.salle %></td>
          <td><%= group.tache %></td>
          <!-- <td><%= link_to 'Show', group %></td> -->
          <td><%= link_to 'Edit', edit_group_path(group) %></td>
          <td>
            <button type="button" name="button"><%= link_to 'Clearteam', clearteam_path(group) %></button>
          </td>

          <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td>

            <div class="col-lg-offset-2">

              <% @people.each do |person|%>
              <p>
                <% if group.id == person.group_id%>
                <%= person.name%>
                <%if person.sensei%>

                ==> SENSEI!
                <%else%>
                ==> eleve
                <%end%>
                <br>
                <%=link_to "Change status", updatesensei_path(person)%>
                <br>
                <% end %>
              </p>
              <% end %>

            </td>
          </tr>
        </div>

        <% end %>

      </tbody>
    </table>

    <br>

    <button type="button" name="button"><%= link_to 'New Group', new_group_path %></button>

    <p id="notice"><%= notice %></p>

    <div class=" col-lg-offset-4">

      <h1>Listing People</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <!-- <th>Email</th>
      <th>Tel</th> -->
            <!-- <th>Group</th> -->
            <th>Sensei</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @people.each do |person| %>
          <tr>
            <% if person.group_id == nil %>
            <td><%= person.name %></td>
            <td><%= person.sensei %></td>
            <%end%>
          </tr>
          <% end %>
        </tbody>
      </table>
      <button type="button" name="button">
        <%=link_to 'randomize', randomize_path%></button>
      <br>
    </div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name group:</strong>
  <%= @group.name_group %>
</p>

<p>
  <strong>Salle:</strong>
  <%= @group.salle %>
</p>

<p>
  <strong>Tache:</strong>
  <%= @group.tache %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RandGroup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Email</th>
      <th>Tel</th> -->
      <th>Group</th>
      <th>Sensei</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
         <!-- <td><%= person.email %></td> -->
        <!-- <td>0<%= person.tel %></td> -->
         <td><%= person.group_id %></td>
        <td><%= person.sensei %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>